apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bmwload01
  namespace: bmw
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: cfd
        team: bmw
    spec:
      containers:
      - name: bmwload01-ctr
        image: polinux/stress
        resources:
          limits:
            cpu: 40m
        command: ["stress"]
        args: ["--cpu", "1", "--vm", "1", "--vm-bytes", "17M"]

