apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ferrariload02
  namespace: ferrari
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: db
        team: ferrari
    spec:
      containers:
      - name: ferrariload02-ctr
        image: polinux/stress
        resources:
          limits:
            cpu: 60m
        command: ["stress"]
        args: ["--cpu", "1", "--vm", "2", "--vm-bytes", "200M"]

