apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: renault01
  namespace: renault
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cfd
        team: renault
    spec:
      containers:
      - name: renaultload01-ctr
        image: polinux/stress
        command: ["stress"]
        args: ["--cpu", "1", "--vm", "1", "--vm-bytes", "17M"]

