apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: renault02
  namespace: renault
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: cad
        team: renault
    spec:
      containers:
      - name: renaultload02-ctr
        image: polinux/stress
        resources:
          limits:
            cpu: 40m
        command: ["stress"]
        args: ["--cpu", "1", "--vm", "4", "--vm-bytes", "35M"]

