apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bmwloader
  namespace: bmw
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stress
        team: bmw
    spec:
      containers:
      - name: stress
        image: progrium/stress
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        args:
        - "--
